[metadata]
name = "dfint localization hook offsets"
version = "51.07 steam win64"
checksum = 0x67CEFDF1

[offsets]
string_copy_n = 0x20310
string_append_n = 0x20450
std_string_ctor = 0x2D7E0
addst = 0xA0BA90
addst_top = 0xA0BB70
addst_flag = 0xA0B9A0
standardstringentry = 0xB2FC80
simplify_string = 0x4A7370
upper_case_string = 0x4A76B0
lower_case_string = 0x4A7510
capitalize_string_words = 0x4A7850
capitalize_string_first_word = 0x4A7AE0