[metadata]
name = "dfint localization hook offsets"
version = "51.08 classic win64"
checksum = 0x67D2A84A

[offsets]
string_copy_n = 0x20290
string_append_n = 0x203D0
std_string_ctor = 0x2D760
addst = 0xA038E0
addst_top = 0xA039C0
addst_flag = 0xA037F0
standardstringentry = 0xB27110
simplify_string = 0x49F520
upper_case_string = 0x49F860
lower_case_string = 0x49F6C0
capitalize_string_words = 0x49FA00
capitalize_string_first_word = 0x49FC90