[metadata]
name = "dfint localization hook offsets"
version = "51.04 steam win64"
checksum = 0x6797A2CA

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D740
addst = 0xA03EC0
addst_top = 0xA03FA0
addst_flag = 0xA03DD0
standardstringentry = 0xB26C90
simplify_string = 0x4A5680
upper_case_string = 0x4A59C0
lower_case_string = 0x4A5820
capitalize_string_words = 0x4A5B60
capitalize_string_first_word = 0x4A5DF0