[metadata]
name = "dfint localization hook offsets"
version = "51.05 itch.io win64"
checksum = 0x67A8EAD4

[offsets]
string_copy_n = 0x20250
string_append_n = 0x20390
std_string_ctor = 0x2D6C0
addst = 0xA072B0
addst_top = 0xA07390
addst_flag = 0xA071C0
standardstringentry = 0xB2B3C0
simplify_string = 0x4A3A40
upper_case_string = 0x4A3D80
lower_case_string = 0x4A3BE0
capitalize_string_words = 0x4A3F20
capitalize_string_first_word = 0x4A41B0