[metadata]
name = "dfint localization hook offsets"
version = "51.01 steam win64"
checksum = 0x678F759E

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D740
addst = 0xA03550
addst_top = 0xA03630
addst_flag = 0xA03460
standardstringentry = 0xB262F0
simplify_string = 0x4A5A00
upper_case_string = 0x4A5D40
lower_case_string = 0x4A5BA0
capitalize_string_words = 0x4A5EE0
capitalize_string_first_word = 0x4A6170