[metadata]
name = "dfint localization hook offsets"
version = "51.02 classic win64"
checksum = 0x67910A8D

[offsets]
string_copy_n = 0x20250
string_append_n = 0x20390
std_string_ctor = 0x2D6C0
addst = 0x9FC350
addst_top = 0x9FC430
addst_flag = 0x9FC260
standardstringentry = 0xB1E760
simplify_string = 0x49DC60
upper_case_string = 0x49DFA0
lower_case_string = 0x49DE00
capitalize_string_words = 0x49E140
capitalize_string_first_word = 0x49E3D0