[metadata]
name = "dfint localization hook offsets"
version = "51.08 itch.io win64"
checksum = 0x67D2A139

[offsets]
string_copy_n = 0x20290
string_append_n = 0x203D0
std_string_ctor = 0x2D760
addst = 0xA08E40
addst_top = 0xA08F20
addst_flag = 0xA08D50
standardstringentry = 0xB2D030
simplify_string = 0x4A4A20
upper_case_string = 0x4A4D60
lower_case_string = 0x4A4BC0
capitalize_string_words = 0x4A4F00
capitalize_string_first_word = 0x4A5190