[metadata]
name = "dfint localization hook offsets"
version = "51.03 steam win64"
checksum = 0x6795100C

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D740
addst = 0xA03DF0
addst_top = 0xA03ED0
addst_flag = 0xA03D00
standardstringentry = 0xB26BC0
simplify_string = 0x4A55B0
upper_case_string = 0x4A58F0
lower_case_string = 0x4A5750
capitalize_string_words = 0x4A5A90
capitalize_string_first_word = 0x4A5D20