[metadata]
name = "dfint localization hook offsets"
version = "51.07 itch.io win64"
checksum = 0x67CF0628

[offsets]
string_copy_n = 0x20290
string_append_n = 0x203D0
std_string_ctor = 0x2D760
addst = 0xA08E90
addst_top = 0xA08F70
addst_flag = 0xA08DA0
standardstringentry = 0xB2D080
simplify_string = 0x4A4A40
upper_case_string = 0x4A4D80
lower_case_string = 0x4A4BE0
capitalize_string_words = 0x4A4F20
capitalize_string_first_word = 0x4A51B0