[metadata]
name = "dfint localization hook offsets"
version = "51.02 steam win64"
checksum = 0x6790F799

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D740
addst = 0xA04420
addst_top = 0xA04500
addst_flag = 0xA04330
standardstringentry = 0xB271F0
simplify_string = 0x4A5A20
upper_case_string = 0x4A5D60
lower_case_string = 0x4A5BC0
capitalize_string_words = 0x4A5F00
capitalize_string_first_word = 0x4A6190