[metadata]
name = "dfint localization hook offsets"
version = "51.06 steam win64"
checksum = 0x67BDACC9

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D740
addst = 0xA0A690
addst_top = 0xA0A770
addst_flag = 0xA0A5A0
standardstringentry = 0xB2E7A0
simplify_string = 0x4A6890
upper_case_string = 0x4A6BD0
lower_case_string = 0x4A6A30
capitalize_string_words = 0x4A6D70
capitalize_string_first_word = 0x4A7000