[metadata]
name = "dfint localization hook offsets"
version = "51.06 classic win64"
checksum = 0x67BDBCD2

[offsets]
string_copy_n = 0x20250
string_append_n = 0x20390
std_string_ctor = 0x2D6C0
addst = 0xA024F0
addst_top = 0xA025D0
addst_flag = 0xA02400
standardstringentry = 0xB25C40
simplify_string = 0x49EA00
upper_case_string = 0x49ED40
lower_case_string = 0x49EBA0
capitalize_string_words = 0x49EEE0
capitalize_string_first_word = 0x49F170