[metadata]
name = "dfint localization hook offsets"
version = "51.08 steam win64"
checksum = 0x67D29900

[offsets]
string_copy_n = 0x20310
string_append_n = 0x20450
std_string_ctor = 0x2D7E0
addst = 0xA0BA40
addst_top = 0xA0BB20
addst_flag = 0xA0B950
standardstringentry = 0xB2FC30
simplify_string = 0x4A7350
upper_case_string = 0x4A7690
lower_case_string = 0x4A74F0
capitalize_string_words = 0x4A7830
capitalize_string_first_word = 0x4A7AC0