[metadata]
name = "dfint localization hook offsets"
version = "51.05 steam win64"
checksum = 0x67A8DE8B

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D740
addst = 0xA09EF0
addst_top = 0xA09FD0
addst_flag = 0xA09E00
standardstringentry = 0xB2E000
simplify_string = 0x4A63D0
upper_case_string = 0x4A6710
lower_case_string = 0x4A6570
capitalize_string_words = 0x4A68B0
capitalize_string_first_word = 0x4A6B40