[metadata]
name = "dfint localization hook offsets"
version = "51.03 itch.io win64"
checksum = 0x6795253D

[offsets]
string_copy_n = 0x20250
string_append_n = 0x20390
std_string_ctor = 0x2D6C0
addst = 0xA01280
addst_top = 0xA01360
addst_flag = 0xA01190
standardstringentry = 0xB24050
simplify_string = 0x4A2CF0
upper_case_string = 0x4A3030
lower_case_string = 0x4A2E90
capitalize_string_words = 0x4A31D0
capitalize_string_first_word = 0x4A3460