[metadata]
name = "dfint localization hook offsets"
version = "51.13 classic win64"
checksum = 0x685DC50E

[offsets]
string_copy_n = 0x20160
string_append_n = 0x202A0
std_string_ctor = 0x2D630
addst = 0xA1A840
addst_top = 0xA1A920
addst_flag = 0xA1A750
standardstringentry = 0xB3E500
simplify_string = 0x4AC7C0
upper_case_string = 0x4ACB00
lower_case_string = 0x4AC960
capitalize_string_words = 0x4ACCA0
capitalize_string_first_word = 0x4ACF30