[metadata]
name = "dfint localization hook offsets"
version = "51.12 classic win64"
checksum = 0x685D0797

[offsets]
string_copy_n = 0x20160
string_append_n = 0x202A0
std_string_ctor = 0x2D630
addst = 0xA1A640
addst_top = 0xA1A720
addst_flag = 0xA1A550
standardstringentry = 0xB3E300
simplify_string = 0x4AC700
upper_case_string = 0x4ACA40
lower_case_string = 0x4AC8A0
capitalize_string_words = 0x4ACBE0
capitalize_string_first_word = 0x4ACE70