[metadata]
name = "dfint localization hook offsets"
version = "51.11 itch.io win64"
checksum = 0x680527DD

[offsets]
string_copy_n = 0x20150
string_append_n = 0x20290
std_string_ctor = 0x2D620
addst = 0xA0B360
addst_top = 0xA0B440
addst_flag = 0xA0B270
standardstringentry = 0xB2F1C0
simplify_string = 0x4A6760
upper_case_string = 0x4A6AA0
lower_case_string = 0x4A6900
capitalize_string_words = 0x4A6C40
capitalize_string_first_word = 0x4A6ED0