[metadata]
name = "dfint localization hook offsets"
version = "51.10 itch.io win64"
checksum = 0x67EE68A8

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D7A0
addst = 0xA086D0
addst_top = 0xA087B0
addst_flag = 0xA085E0
standardstringentry = 0xB2C8B0
simplify_string = 0x4A4810
upper_case_string = 0x4A4B50
lower_case_string = 0x4A49B0
capitalize_string_words = 0x4A4CF0
capitalize_string_first_word = 0x4A4F80