[metadata]
name = "dfint localization hook offsets"
version = "51.10 classic win64"
checksum = 0x67EE7339

[offsets]
string_copy_n = 0x202D0
string_append_n = 0x20410
std_string_ctor = 0x2D7A0
addst = 0xA03170
addst_top = 0xA03250
addst_flag = 0xA03080
standardstringentry = 0xB26990
simplify_string = 0x49F310
upper_case_string = 0x49F650
lower_case_string = 0x49F4B0
capitalize_string_words = 0x49F7F0
capitalize_string_first_word = 0x49FA80