[metadata]
name = "dfint localization hook offsets"
version = "51.13 steam win64"
checksum = 0x685DCDA8

[offsets]
string_copy_n = 0x201D0
string_append_n = 0x20310
std_string_ctor = 0x2D6A0
addst = 0xA1D360
addst_top = 0xA1D440
addst_flag = 0xA1D270
standardstringentry = 0xB41020
simplify_string = 0x4AF010
upper_case_string = 0x4AF350
lower_case_string = 0x4AF1B0
capitalize_string_words = 0x4AF4F0
capitalize_string_first_word = 0x4AF780