[metadata]
name = "dfint localization hook offsets"
version = "51.11 steam win64"
checksum = 0x68052F4D

[offsets]
string_copy_n = 0x201D0
string_append_n = 0x20310
std_string_ctor = 0x2D6A0
addst = 0xA0DE90
addst_top = 0xA0DF70
addst_flag = 0xA0DDA0
standardstringentry = 0xB31CF0
simplify_string = 0x4A8FC0
upper_case_string = 0x4A9300
lower_case_string = 0x4A9160
capitalize_string_words = 0x4A94A0
capitalize_string_first_word = 0x4A9730