[metadata]
name = "dfint localization hook offsets"
version = "52.03 other win64"
checksum = 0x68949E86

[offsets]
string_copy_n = 0x75770
string_append_n = 0x758B0
std_string_ctor = 0x6DED0
addst = 0xA92E70
addst_top = 0xA92F50
addst_flag = 0xA92D80
standardstringentry = 0xBF1830
simplify_string = 0x511BC0
upper_case_string = 0x511F00
lower_case_string = 0x511D60
capitalize_string_words = 0x5120A0
capitalize_string_first_word = 0x512330