[metadata]
name = "dfint localization hook offsets"
version = "52.01 classic win64"
checksum = 0x687E03AE

[offsets]
string_copy_n = 0x756A0
string_append_n = 0x757E0
std_string_ctor = 0x6DE00
addst = 0xA7E110
addst_top = 0xA7E1F0
addst_flag = 0xA7E020
standardstringentry = 0xBDCE90
simplify_string = 0x505AC0
upper_case_string = 0x505E00
lower_case_string = 0x505C60
capitalize_string_words = 0x505FA0
capitalize_string_first_word = 0x506230