[metadata]
name = "dfint localization hook offsets"
version = "52.04 steam win64"
checksum = 0x68B08095

[offsets]
string_copy_n = 0x757F0
string_append_n = 0x75930
std_string_ctor = 0x6DF50
addst = 0xA98C90
addst_top = 0xA98D70
addst_flag = 0xA98BA0
standardstringentry = 0xBF7740
simplify_string = 0x516240
upper_case_string = 0x516580
lower_case_string = 0x5163E0
capitalize_string_words = 0x516720
capitalize_string_first_word = 0x5169B0