[metadata]
name = "dfint localization hook offsets"
version = "52.02 steam win64"
checksum = 0x6881EB40

[offsets]
string_copy_n = 0x75710
string_append_n = 0x75850
std_string_ctor = 0x6DE70
addst = 0xA82930
addst_top = 0xA82A10
addst_flag = 0xA82840
standardstringentry = 0xBE1780
simplify_string = 0x508560
upper_case_string = 0x5088A0
lower_case_string = 0x508700
capitalize_string_words = 0x508A40
capitalize_string_first_word = 0x508CD0