[metadata]
name = "dfint localization hook offsets"
version = "52.04 other win64"
checksum = 0x68B08BDF

[offsets]
string_copy_n = 0x75780
string_append_n = 0x758C0
std_string_ctor = 0x6DEE0
addst = 0xA95A00
addst_top = 0xA95AE0
addst_flag = 0xA95910
standardstringentry = 0xBF44B0
simplify_string = 0x513910
upper_case_string = 0x513C50
lower_case_string = 0x513AB0
capitalize_string_words = 0x513DF0
capitalize_string_first_word = 0x514080