[metadata]
name = "dfint localization hook offsets"
version = "52.05 steam win64"
checksum = 0x68D64CE7

[offsets]
string_copy_n = 0x75840
string_append_n = 0x75980
std_string_ctor = 0x6DFA0
addst = 0xA994F0
addst_top = 0xA995D0
addst_flag = 0xA99400
standardstringentry = 0xBF7FA0
simplify_string = 0x5163A0
upper_case_string = 0x5166E0
lower_case_string = 0x516540
capitalize_string_words = 0x516880
capitalize_string_first_word = 0x516B10