[metadata]
name = "dfint localization hook offsets"
version = "52.02 other win64"
checksum = 0x6881F7EC

[offsets]
string_copy_n = 0x756A0
string_append_n = 0x757E0
std_string_ctor = 0x6DE00
addst = 0xA7F600
addst_top = 0xA7F6E0
addst_flag = 0xA7F510
standardstringentry = 0xBDE450
simplify_string = 0x505B80
upper_case_string = 0x505EC0
lower_case_string = 0x505D20
capitalize_string_words = 0x506060
capitalize_string_first_word = 0x5062F0