[metadata]
name = "dfint localization hook offsets"
version = "52.01 steam win64"
checksum = 0x687DF415

[offsets]
string_copy_n = 0x75710
string_append_n = 0x75850
std_string_ctor = 0x6DE70
addst = 0xA813E0
addst_top = 0xA814C0
addst_flag = 0xA812F0
standardstringentry = 0xBE0160
simplify_string = 0x508440
upper_case_string = 0x508780
lower_case_string = 0x5085E0
capitalize_string_words = 0x508920
capitalize_string_first_word = 0x508BB0