[metadata]
name = "dfint localization hook offsets"
version = "52.03 steam win64"
checksum = 0x689495FD

[offsets]
string_copy_n = 0x757E0
string_append_n = 0x75920
std_string_ctor = 0x6DF40
addst = 0xA960D0
addst_top = 0xA961B0
addst_flag = 0xA95FE0
standardstringentry = 0xBF4A90
simplify_string = 0x5144E0
upper_case_string = 0x514820
lower_case_string = 0x514680
capitalize_string_words = 0x5149C0
capitalize_string_first_word = 0x514C50